# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64c2d87b96ae07643d7269e874a8e61b"
name = "Circular-Wealth-Tracking"
handle = "circular-wealth-tracking"
application_url = "https://buffalo-diagnosis-rick-impaired.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://5ca3-93-140-158-222.ngrok-free.app/app-uninstalled-webhook"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://5ca3-93-140-158-222.ngrok-free.app/order-webhook"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_metaobjects,write_products,read_themes,write_themes,read_products,write_script_tags,read_script_tags,write_customers,read_customers,write_orders,read_orders,write_draft_orders,read_draft_orders,write_price_rules,read_price_rules,write_discounts,read_discounts,write_fulfillments,read_fulfillments,read_cart_transforms"

[auth]
redirect_urls = [
  "https://buffalo-diagnosis-rick-impaired.trycloudflare.com/auth/callback",
  "https://buffalo-diagnosis-rick-impaired.trycloudflare.com/auth/shopify/callback",
  "https://buffalo-diagnosis-rick-impaired.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
