# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3936f39facea21589f6caaf2e12a29ec"
name = "Test11"
handle = "test11-28"
application_url = "https://circular-tracking-test11.vercel.app/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://c42b-93-140-177-43.ngrok-free.app/app-uninstalled-webhook"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://c42b-93-140-177-43.ngrok-free.app/order-webhook"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,read_customers,read_discounts,read_draft_orders,read_fulfillments,read_orders,read_price_rules,read_products,read_script_tags,read_themes,unauthenticated_read_metaobjects,write_customers,write_discounts,write_draft_orders,write_fulfillments,write_orders,write_price_rules,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://circular-tracking-test11.vercel.app/auth/callback",
]

[pos]
embedded = false
